### PR TITLE
Remove B+ and B- pins

### PR DESCRIPTION
**Pull request by Nicell**
Thanks for making this footprint for everyone. The B+ and B- pins should not be used, as they are not part of the Pro Micro pinout and also are subject to being removed in the future. Instead, RAW and GND should be used, so I've updated this footprint to fit that change.

### CODE REVIEW

**Comment by bstiq** [comment]
thank you !

**Comment by infused-kim** [comment]
@Nicell do you have a source for the fact that these pins are subject to being removed and that they shouldn't be used?

[Nice!Nano's documentation says](https://nicekeyboards.com/docs/nice-nano/getting-started)...

> If you choose to solder your battery, use the B+ and B- pins. B+ is for the positive, red wire, and the B- pin is for the negative, black wire.

if it's official that these pins shouldn't be used and are subject to being removed, then the nice!nano documentation should be updated.

And I think the README of this repo should also be updated to explain why the pins are missing even though they are recommended to be used in the documentation.

Or perhaps the library can be expanded to have both versions of the nice!nano.

I was very surprised the pins were missing and only realized why once I checked the fork graph.

If something changed and these are not subject to be removed anymore, then perhaps we should reverse this change.

What do you guys think?

**Comment by Nicell** [comment]
Hi @infused-kim, source is me. It's true that the B+ and B- pins should be used when soldering your battery to the nice!nano, but when designing a board from scratch, the RAW and GND pins should be used instead as they follow the Pro Micro pinout. The B+ and B- pins are bodge pins for existing board designs. Please read [this section of the nice!nanos documentation](https://nicekeyboards.com/docs/nice-nano/getting-started#before-you-start):

> If you need to use these pins with your PCB, RAW and GND are the respective equivalents to B+ and B-

B+ and B- should **NOT** be used for designs accommodating the nice!nano as it defeats the purpose of the Pro Micro pinout. The nice!nano v2 even changes the B+ and B- holes so that they do not work with any pin headers to avoid people trying to use them on their boards.

**Comment by infused-kim** [comment]
> Hi @infused-kim, source is me.

Sorry, I didn't realize that you are actually the founder of nice!... :)

Thank you for clarifying.

**Pull request merged**
